# Generated by Django 5.1.7 on 2025-05-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_payment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
